### ISSUE TITLE
Module parse failed: Unexpected token (200:6) You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by 4dcode** [apriady/ovoid-nodejs#2]
I'm trying to use your code in a vue app using NodeJS

ERROR  Failed to compile with 1 errors                                                                                                               6:35:08 PM

 error  in ./node_modules/ovoid/src/index.js

Module parse failed: Unexpected token (200:6)
You may need an appropriate loader to handle this file type.
|     return {
|       'Authorization': this.authToken,
|       ...this.headers
|     }
|   }

 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/views/MyAccount.vue 436:12-28
 @ ./src/views/MyAccount.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8081 webpack/hot/dev-server ./src/main.js

**Comment by apriady** [comment]
Hi,
Can i look at the code that you use when calling this plugin?

**Comment by 4dcode** [comment]
Hi,

Thank you for your response.
Attached the file.

npm install is done.
On line 433 " const OVOID = require('ovoid') " I include the ovoid.
On line 585 (linkOvoWallet) I try to do the ovoid.login2FA.

Kind Regards,
Martin

[MyAccount.vue.zip](https://github.com/apriady/ovoid-nodejs/files/3747459/MyAccount.vue.zip)

**Comment by alimuddinhasan** [comment]
> Hi,
> 
> Thank you for your response.
> Attached the file.
> 
> npm install is done.
> On line 433 " const OVOID = require('ovoid') " I include the ovoid.
> On line 585 (linkOvoWallet) I try to do the ovoid.login2FA.
> 
> Kind Regards,
> Martin
> 
> [MyAccount.vue.zip](https://github.com/apriady/ovoid-nodejs/files/3747459/MyAccount.vue.zip)

Hi,
Do your javascript version support spread operator like `...this.headers`?
If not please try to update to ES6 and try again

**Comment by 4dcode** [comment]
Hi,
My system says I'm on ES6 but  but still did not work in the first place.

I changed the code on line 197 in index.js to the code below and after that it's working without errors.
See this link: http://es6-features.org/#SpreadOperator

Thanks for your support.
Martin

_aditionalHeader() {
    return {
      'Authorization': this.authToken.concat(this.headers)
      // ...this.headers
    }
  }
