### ISSUE TITLE
magic link tidak bisa dibuka, "hanya bisa dari ponsel yang sama"

### ISSUE THREAD

**Issue by laurentiusedrick** [apriady/ovoid-nodejs#25]
ovoid.login2FA()
Setiap berusaha membuka magic link untuk mendapatkan OTP dengan nomer yang benar, selalu tampilannya seperti ini:
![image](https://user-images.githubusercontent.com/63906925/147461503-1da00062-d32e-454d-b671-bb5c89c37e6f.jpg)

**Comment by apriady** [comment]
https://github.com/apriady/ovoid-nodejs/issues/23#issuecomment-939265066
