### ISSUE TITLE
loginSecurityCode Error

### ISSUE THREAD

**Issue by radensoft** [apriady/ovoid-nodejs#3]
loginSecurityCode(securityCode, updateAccessToken) {
    let data = {
      'deviceUnixtime': Math.floor(new Date() / 1000),
      'securityCode': securityCode,
      'updateAccessToken': updateAccessToken,
      'message': ''
    };
    return ovo.post('v2.0/api/auth/customer/loginSecurityCode/verify', data, this.headers)
  }

**Comment by adam080880** [comment]
i got same error with you

**Comment by adam080880** [comment]
i got same error, has anyone found a way to fix this problem?

**Comment by mohamadihsan** [comment]
belum ada update an lg buat error diatas? atau apakah ada yg udh solve untuk masalah diatas?

**Comment by apriady** [comment]
Hi, Sorry for very late response 😿 

Can you try again using v1.2.1 ?
I have update the documentation also, there are some parameter that unclear in previous version of documentation.
